[package]
name = "bevy_assets_tar_zstd_bundler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
tar = "0.4.38"
zstd = "0"
